language: java
deploy:
  provider: heroku
  api_key:
    secure: uWlYu5eCeTvh9LhDa0CZqshmmVTOzER5jbT1bWcxHiw7TAN6yd7Jf62Cm8pVzl6XdFGALMsCGLA5Mz6CGzELigWIu8OkqchukbtDo3UkE8SG5oYvu3BsOcgxPsWeLBMakII7RBXErDQZ6jMjR4uNl8d4/QejvO/AH/gRNfnBElsk6IPrXOVIos1dJGj5RjchZaCXJW4QMpG1XIyX9JMP51RRVJbHgoJqQM3nk/L7X8wkJzDOmKmZ+iO9XnU4pHZgH2V5ESD6LNyCH30Y+t4HuW1WQ15tFzrg7fhdp2kn0lEDclv6hNQcnIap59p/M1GKouotXqfxizEqujEjx5gDhpmsagxi4rbyvQxmWNtROUthXfw+Vm8uzeGx6Kr4SglOqh6mQl0RosEo/9tWtj5UUnSWWxVGOOxgPPVrCKuYKuq9/Vm+ZtYPATpMeE35J15wexAVQzH22G7uuALPv1XJqLIsexgHIPndfWlh6CB4wOMwYgbBk5Pxp35wd9omWLenmiu1jQMOHX8I7jboUKFF+8iPsPnbSZM7HsCBEGFt/419NA0SE3E7jBABVzJB+vC0q04aPtHyjwIDd7tF1C4JR62tn0PLSpLj4Zb/KAuv2UQQ2XRblqbDqoYhX+JpRj5gvh/903rkDE7lCvRK5MUeqk6xNmawfpQUzyDxHD0YV5o=
  app: shielded-bayou-74829
